name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build and Push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: sresthjay/my-python-app:latest

      # 5. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 6. Setup EC2 SSH Key
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/my-devops-key.pem
          chmod 600 ~/.ssh/my-devops-key.pem

      # 7. Deploy container on EC2
      - name: Deploy Docker Container on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          CONTAINER_NAME: my-cloud-app
          IMAGE_NAME: sresthjay/my-python-app:latest

        run: |
          ssh -i ~/.ssh/my-devops-key.pem \
          -o StrictHostKeyChecking=no \
          ubuntu@$EC2_HOST << EOF

          sudo docker stop $CONTAINER_NAME || true
          sudo docker rm $CONTAINER_NAME || true

          sudo docker pull $IMAGE_NAME

          sudo docker run -d \
            --name $CONTAINER_NAME \
            -p 8080:8080 \
            $IMAGE_NAME

          EOF
